/*
 * File: app/view/EmailPopup.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.EmailPopup', {
    extend: 'Ext.form.Panel',

    config: {
        height: '50%',
        id: 'email_popup',
        width: '100%',
        modal: true,
        items: [
            {
                xtype: 'textfield',
                id: 'email_address',
                label: 'Email',
                name: 'email_address'
            },
            {
                xtype: 'button',
                id: 'send',
                itemId: 'mybutton3',
                ui: 'confirm',
                iconCls: 'action'
            },
            {
                xtype: 'button',
                id: 'cancel',
                itemId: 'mybutton25',
                text: 'Cancel'
            }
        ],
        listeners: [
            {
                fn: 'onSendTap',
                event: 'tap',
                delegate: '#send'
            },
            {
                fn: 'onCancelTap',
                event: 'tap',
                delegate: '#cancel'
            }
        ]
    },

    onSendTap: function(button, e, eOpts) {
        var Record=Ext.getCmp('email_popup').getRecord();
        var Email=Ext.getCmp('email_address').getValue();

        Ext.util.JSONP.request({
            url: 'http://www.gpsname.com/index.php/feed/email_gpsname',
            callbackKey: 'callback',
            params: {email: Email,id:Record.data.id},
            success: function(response, request) {
                // Unmask the viewport
                Ext.Viewport.unmask();
                if (response.result !='OK')
                {
                    Ext.Msg.alert('Email', response.message);
                }
            }
        });
        Ext.getCmp('email_popup').destroy();
    },

    onCancelTap: function(button, e, eOpts) {
        Ext.getCmp('email_popup').destroy();
    }

});