/*
 * File: app/view/main.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.main', {
    extend: 'Ext.tab.Panel',

    config: {
        id: 'mainPanel',
        tabBar: {
            docked: 'bottom',
            height: '50px',
            hidden: false,
            id: 'navToolbar',
            itemId: 'navToolbar',
            ui: 'light'
        },
        items: [
            {
                xtype: 'tabpanel',
                title: 'Place',
                iconCls: 'maps',
                id: 'placeContainer',
                itemId: 'mytabpanel4',
                items: [
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        id: 'placeNavigation',
                        itemId: '',
                        layout: {
                            pack: 'center',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                height: '40px',
                                id: 'nokiaBtn',
                                itemId: 'nokiaBtn',
                                style: 'font-size:0.75em;',
                                ui: 'action',
                                iconAlign: 'top',
                                iconCls: 'arrow_up',
                                text: 'Nokia'
                            },
                            {
                                xtype: 'button',
                                height: '40px',
                                id: 'googleBtn',
                                itemId: 'google_button1',
                                style: 'font-size:0.75em;',
                                ui: 'action',
                                iconAlign: 'top',
                                iconCls: 'arrow_up',
                                text: 'Google'
                            },
                            {
                                xtype: 'button',
                                height: '40px',
                                hidden: true,
                                id: 'layarBtn',
                                itemId: 'mybutton3',
                                style: 'font-size:0.75em;',
                                ui: 'action',
                                text: 'Layar'
                            },
                            {
                                xtype: 'button',
                                height: '40px',
                                hidden: false,
                                id: 'wazeBtn',
                                itemId: 'waze_button1',
                                style: 'font-size:0.75em;',
                                ui: 'action',
                                iconAlign: 'top',
                                iconCls: 'arrow_up',
                                text: 'Waze'
                            },
                            {
                                xtype: 'button',
                                height: '40px',
                                id: 'placeSendBtn',
                                itemId: 'mybutton13',
                                style: 'font-size:0.75em;',
                                ui: 'action',
                                iconAlign: 'top',
                                iconCls: 'action',
                                text: 'Send'
                            },
                            {
                                xtype: 'button',
                                height: '40px',
                                id: 'placeClearBtn',
                                itemId: 'mybutton18',
                                style: 'font-size:0.75em;',
                                ui: 'action',
                                iconAlign: 'top',
                                iconCls: 'delete',
                                text: 'Clear'
                            }
                        ]
                    },
                    {
                        xtype: 'formpanel',
                        title: 'Details',
                        id: 'placeDetailsForm',
                        items: [
                            {
                                xtype: 'fieldset',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        id: 'title',
                                        label: 'Title',
                                        labelWidth: '40%',
                                        name: 'title'
                                    },
                                    {
                                        xtype: 'togglefield',
                                        itemId: 'mytogglefield',
                                        label: 'GPS',
                                        labelWidth: '40%',
                                        name: 'gpsToggle'
                                    },
                                    {
                                        xtype: 'numberfield',
                                        id: 'lat',
                                        style: 'float:left;',
                                        width: '50%',
                                        inputCls: 'small',
                                        label: 'Lat',
                                        labelWidth: '36%',
                                        name: 'lat'
                                    },
                                    {
                                        xtype: 'numberfield',
                                        id: 'lon',
                                        width: '50%',
                                        inputCls: 'small',
                                        label: 'Lon',
                                        labelWidth: '36%',
                                        name: 'lon'
                                    },
                                    {
                                        xtype: 'selectfield',
                                        id: 'permissions',
                                        width: '80%',
                                        label: 'Permissions',
                                        labelWidth: '50%',
                                        name: 'permissions',
                                        options: [
                                            {
                                                text: 'public',
                                                value: 'public'
                                            },
                                            {
                                                text: 'private',
                                                value: 'private'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        layout: {
                                            type: 'hbox'
                                        },
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                hidden: false,
                                                id: 'tagged',
                                                itemId: 'mytextfield1',
                                                width: '80%',
                                                label: 'Tagged',
                                                labelWidth: '50%',
                                                name: 'tagged',
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'image',
                                                height: 37,
                                                id: 'iconImg',
                                                itemId: '',
                                                margin: '8px',
                                                minWidth: '32px',
                                                padding: '4px',
                                                width: '32px',
                                                src: 'images/icons/addIcon.png'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'textfield',
                                        hidden: true,
                                        id: 'image',
                                        label: 'Image',
                                        labelWidth: '40%',
                                        name: 'image',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'container',
                                        height: '60px',
                                        layout: {
                                            type: 'hbox'
                                        },
                                        items: [
                                            {
                                                xtype: 'button',
                                                id: 'placeAddBtn',
                                                minHeight: 37,
                                                style: 'margin:8px;',
                                                ui: 'confirm',
                                                width: '25%',
                                                iconCls: 'add',
                                                text: ''
                                            },
                                            {
                                                xtype: 'button',
                                                id: 'placeDeleteBtn',
                                                itemId: 'mybutton8',
                                                minHeight: 37,
                                                style: 'margin:8px;',
                                                ui: 'decline',
                                                width: '25%',
                                                iconCls: 'trash',
                                                text: ''
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        title: 'Map',
                        id: 'myMap',
                        itemId: 'mycontainer',
                        layout: {
                            type: 'fit'
                        },
                        items: [
                            {
                                xtype: 'map',
                                id: 'googlemap_add',
                                itemId: 'mymap'
                            },
                            {
                                xtype: 'list',
                                height: '300px;',
                                hidden: true,
                                id: 'peopleContainer',
                                itemId: '',
                                itemTpl: [
                                    '<div',
                                    '<tpl if="connectionstatus == \'Connected\'"> style="color:green;"</tpl>',
                                    '<tpl if="connectionstatus == \'Connect?\'"> style="color:orange;"</tpl>',
                                    '>',
                                    '{gpsname}',
                                    '</div>'
                                ],
                                grouped: true,
                                onItemDisclosure: false
                            }
                        ]
                    }
                ],
                tabBar: {
                    docked: 'top'
                }
            },
            {
                xtype: 'list',
                title: 'My Places',
                iconCls: 'home',
                id: 'myLocationsContainer',
                itemId: 'mylist',
                ui: 'round',
                itemTpl: [
                    '<div style="height:40px;">',
                    '    <div class="image" style="float:left;height:37px;margin:4px;"><img src="{image}"/></div>',
                    '<div style="color:grey;margin:4px">{title}</div>',
                    '</div>'
                ],
                store: 'MyLocations',
                grouped: true,
                onItemDisclosure: false
            },
            {
                xtype: 'container',
                title: 'Settings',
                iconCls: 'settings',
                id: 'settingsContainer',
                items: [
                    {
                        xtype: 'fieldset',
                        title: 'Navigation',
                        items: [
                            {
                                xtype: 'checkboxfield',
                                id: 'nokiaNavCheck',
                                itemId: 'mycheckbox',
                                label: 'Nokia'
                            },
                            {
                                xtype: 'checkboxfield',
                                id: 'googleNavCheck',
                                label: 'Google'
                            },
                            {
                                xtype: 'checkboxfield',
                                id: 'wazeNavCheckbox',
                                label: 'Waze'
                            },
                            {
                                xtype: 'checkboxfield',
                                id: 'layarNavCheckbox',
                                label: 'Layar'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'tabpanel',
                title: 'Settings',
                iconCls: 'settings',
                hidden: true,
                id: 'accountContainer',
                items: [
                    {
                        xtype: 'container',
                        title: 'Account',
                        height: '400px',
                        id: 'account',
                        itemId: 'myformpanel1',
                        items: [
                            {
                                xtype: 'fieldset',
                                title: 'Account Details',
                                items: [
                                    {
                                        xtype: 'emailfield',
                                        id: 'username',
                                        label: 'username',
                                        labelWidth: '40%',
                                        placeHolder: 'email@email.com'
                                    },
                                    {
                                        xtype: 'passwordfield',
                                        id: 'password',
                                        label: 'password',
                                        labelWidth: '40%'
                                    },
                                    {
                                        xtype: 'button',
                                        id: 'login_button',
                                        itemId: 'mybutton4',
                                        style: 'margin:1%',
                                        ui: 'confirm',
                                        text: 'Login'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                html: '<a href="http://www.gpsname.com">GPSName.com</a>',
                                id: 'htmllink',
                                style: 'text-align:center;padding:5px'
                            },
                            {
                                xtype: 'container',
                                centered: false,
                                html: 'Version 3.0',
                                id: 'version',
                                style: 'text-align:center;padding:5px',
                                layout: {
                                    type: 'vbox'
                                }
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        title: 'Create Account',
                        id: 'createAccount',
                        items: [
                            {
                                xtype: 'fieldset',
                                id: 'AddAccountDetails',
                                title: 'Account Details',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        id: 'email_add',
                                        label: 'Email',
                                        labelWidth: '40%',
                                        name: 'email_add'
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'gpsname_add',
                                        label: 'GPSName',
                                        labelWidth: '40%',
                                        name: 'gpsname_add'
                                    },
                                    {
                                        xtype: 'passwordfield',
                                        id: 'password_add',
                                        label: 'Password',
                                        labelWidth: '40%',
                                        name: 'password_add'
                                    },
                                    {
                                        xtype: 'passwordfield',
                                        id: 'password_add_confirm',
                                        label: 'Confirm',
                                        labelWidth: '40%',
                                        name: 'password_add_confirm'
                                    },
                                    {
                                        xtype: 'button',
                                        id: 'add_account_button',
                                        itemId: 'mybutton24',
                                        style: 'margin:1%',
                                        ui: 'confirm',
                                        text: 'Create Account'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMytogglefieldChange',
                event: 'change',
                delegate: '#mytogglefield'
            },
            {
                fn: 'onUser_listItemTap',
                event: 'itemtap',
                delegate: '#peopleContainer'
            },
            {
                fn: 'onNokiaNavCheckChange',
                event: 'change',
                delegate: '#nokiaNavCheck'
            },
            {
                fn: 'onAdd_account_buttonTap',
                event: 'tap',
                delegate: '#add_account_button'
            }
        ]
    },

    onMytogglefieldChange: function(togglefield, newValue, oldValue, eOpts) {
        gpsEnabled=newValue;

        if (gpsEnabled==1){
            GPSMarkerImage='images/icons/1.png';
        }
    },

    onUser_listItemTap: function(dataview, index, target, record, e, eOpts) {
        this.show_places_list= Ext.create('MyApp.view.ShowPlacesUser');
        this.show_places_list.setRecord(record);
        var store = Ext.getStore('Locations');
        store.clearFilter();
        store.load({
            params:{gpsname: record.data.email}
        });    

        Ext.getCmp('users').push(this.show_places_list); 

    },

    onNokiaNavCheckChange: function(checkboxfield, newValue, oldValue, eOpts) {
        if (newValue==true){
            Ext.getCmp('nokiaBtn').show();   
        }
        else
        {
            Ext.getCmp('nokiaBtn').hide();
        }
    },

    onAdd_account_buttonTap: function(button, e, eOpts) {
        var formValues = Ext.getCmp('create_account').getValues();
        var model = Ext.ModelMgr.create(formValues,'MyApp.model.Users');      
        var errors = model.validate(),message = "";
        var errorMessage='';
        if(errors.isValid()){ 

            Ext.util.JSONP.request({
                url: 'http://www.gpsname.com/index.php/login/api_create_gpsname',
                callbackKey: 'callback',
                params: {email:formValues.email_add,gpsname:formValues.gpsname_add,password:formValues.password_add},
                success: function(response, request) {
                    // Unmask the viewport
                    Ext.Viewport.unmask();
                    if (response.result !='OK')
                    {
                        Ext.Msg.alert('Create Error', response.message);
                    } 
                    else 
                    {


                        Ext.Msg.alert('Added!',response.message);

                    }
                }
            });


        } else { 
            errors.each(function (err) {


                errorMessage +="<b>"+err.getField()+"</b> "+err.getMessage()+"<br/>";    


            }); // each()
            Ext.Msg.alert('Form is invalid!', errorMessage);
        }   
    }

});