/*
 * File: app/model/Users.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.Users', {
    extend: 'Ext.data.Model',

    config: {
        fields: [
            {
                name: 'gpsname'
            },
            {
                name: 'gpsid'
            },
            {
                name: 'email'
            },
            {
                name: 'friend'
            },
            {
                name: 'connectionstatus'
            },
            {
                name: 'connection_direction'
            },
            {
                name: 'target_gpsname'
            },
            {
                name: 'target_user_id'
            }
        ]
    }
});