/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({

});

Ext.application({
    models: [
        'Places',
        'Users',
        'Settings',
        'Tags',
        'Lookup',
        'GooglePlaces'
    ],
    stores: [
        'MyLocations',
        'Places',
        'Settings',
        'Tags',
        'Lookup',
        'Tags_edit',
        'GooglePlaces',
        'icons'
    ],
    views: [
        'main',
        'iconChooser'
    ],
    requires: [
        'Ext.MessageBox'
    ],
    controllers: [
        'MainController'
    ],
    name: 'MyApp',

    launch: function() {
        currentLat=0;
        currentLon=0;
        gpsEnabled=0;
        GPSMarkerImage='images/icons/1.png';

        Ext.create('MyApp.view.main', {fullscreen: true});
    }

});
